I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/thelastone.rpy", line 1161, in script
    if E1 >= 2:
  File "game/thelastone.rpy", line 1161, in <module>
    if E1 >= 2:
NameError: name 'E1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/thelastone.rpy", line 1161, in script
    if E1 >= 2:
  File "C:\Users\Cornelius\Desktop\renpy-7.2.2-sdk\renpy\ast.py", line 1807, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Cornelius\Desktop\renpy-7.2.2-sdk\renpy\python.py", line 1961, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Cornelius\Desktop\renpy-7.2.2-sdk\renpy\python.py", line 1954, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/thelastone.rpy", line 1161, in <module>
    if E1 >= 2:
NameError: name 'E1' is not defined

Windows-8-6.2.9200
Ren'Py 7.2.2.491
Get it Right the First Time 0.7
Thu May 30 20:21:00 2019
