I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/thelastone.rpy", line 915, in script
    $ E1 += 2
  File "game/thelastone.rpy", line 915, in <module>
    $ E1 += 2
NameError: name 'E1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/thelastone.rpy", line 915, in script
    $ E1 += 2
  File "C:\Users\Cornelius\Desktop\renpy-7.2.2-sdk\renpy\ast.py", line 900, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Cornelius\Desktop\renpy-7.2.2-sdk\renpy\python.py", line 1930, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/thelastone.rpy", line 915, in <module>
    $ E1 += 2
NameError: name 'E1' is not defined

Windows-8-6.2.9200
Ren'Py 7.2.2.491
Get it Right the First Time 0.7
Thu May 30 17:51:42 2019
